# Generated by Django 3.2.10 on 2023-03-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='descrription',
            new_name='description',
        ),
    ]
